version: '3.8'
services:
  testdb:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - '5433:5432'
    volumes:
      - testdb:/var/lib/postgresql/data
volumes:
  testdb:
    driver: local
