@startuml Shared
title: Shared

!include ./theme.pu 

package Shared {
    class CreatedAt <<DateValueObject>>  {
        _value: Date
    }

    class UpdatedAt <<DateValueObject>>  {
        _value: Date
    }

    note bottom of CreatedAt
    初期時は作成された時間。
    end note 

    note bottom of UpdatedAt
    初期時は作成された時間。
    更新時は既存データより後の日付出なければならない。
    end note 
}

@enduml