name: Integration Tests
on:
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: postgresql://postgres:password@localhost:5433/testdb

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TaskManagementDomain
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-compose
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Run tests
        run: npm run test:it
