name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TaskManagementDomain
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Run tests
        run: npm test:it
